# Generated by Django 3.2.18 on 2023-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antoquinoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('鶏肉', '鶏肉'), ('牛肉', '牛肉'), ('豚肉', '豚肉'), ('麺類', '麺類'), ('魚', '魚'), ('野菜', '野菜'), ('ご飯物', 'ご飯物'), ('その他', 'その他')], max_length=10, null=True),
        ),
    ]
