# Generated by Django 3.2.18 on 2023-08-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antoquinoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
